### ISSUE TITLE
Suggest: key  F12  go to source code of dotnetcore  rather then metadata

### ISSUE THREAD

**Issue by athinboy** [dotnet/foundation#112]
Apology for my poor english!

I have change to Java due to the boss's decision .   I think dotnet  need a big change. In China, more and more dotnet project go to die,  but new java project continuously increase!

I suggest:key  F12  go to source code of dotnetcore  rather then metadata(e.g.    ***.dll.source.zip \****.exe.source.zip),   maybe there is already done,but i don't know. 

thanks!

**Comment by mcmillab** [comment]
great idea, is there any way of doing this?
