### ISSUE TITLE
Missing logo for Steeltoe

### ISSUE THREAD

**Issue by manne** [dotnet/foundation#123]
`https://brandfolder.com/pivotal-assets/attachments/ohxttd-7yxa60-clvf50/pivotal-assets-pivotal-genericfile.png` redirects to a sign in page
https://github.com/dotnet/foundation/blob/c7e513139f593ad95237e864e4d2fdf9181ebafc/projects/projects.json#L128-L130

**Comment by jongalloway** [comment]
Closed by #136
