### ISSUE TITLE
Add Akka.NET to the DNF project listing

### ISSUE THREAD

**Issue by nagytech** [dotnet/foundation#159]
With reference to PR #158 I'm requesting to add Akka.NET to the DNF project listings.

**Comment by nagytech** [comment]
@onovotny Looks like merge #158 was successful, but I'm not seeing Akka.NET on the dotnetfoundation projects listing.  Is this because of the recent rollback which you mentioned in #160?

**Comment by onovotny** [comment]
The rollback shouldn't have anything to do with it, that list should be picked up by the search indexer by automatically after the merge. I can look into it.

**Comment by dnfadmin** [comment]
I see an error in the function index logs: Cannot download markdown file 'Akka.NET'

**Comment by onovotny** [comment]
There was an error in the json file. I've fixed it and it should be fine once it indexes shortly https://github.com/dotnet/foundation/commit/8b87d4fa65656cc0d23c6062faf3d1a1c7d092a0
